#spring.application.name=StudentMicroServiceClient
spring:
  application:
    name: StudentMicroServiceClient
  web:
    error:
      whitelabel:
        enabled: false
  jackson:
    deserialization:
      fail-on-null-for-primitives: false
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 3333